   version: 2
   updates:
     - package-ecosystem: "pip"
       directory: "/"
       schedule:
         interval: "weekly"
       labels:
          - "dependabot:python"
       groups:
          github-actions:
            - "*"

     - package-ecosystem: "github-actions"
       directory: "/"
       schedule:
         interval: "weekly"
       labels:
          - "dependabot:actions"


     - package-ecosystem: "devcontainers"
       directory: "/"
       schedule:
         interval: "weekly"
       labels:
          - "dependabot:devcontainer"
