version: 2
updates:
  # Atualizações de dependências Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependabot:python"

  # Atualizações de GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependabot:actions"

  # Atualizações do Dev Container (Codespaces)
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependabot:devcontainer"
