name: Code Smells

on:
  push:
  pull_request:

jobs:
  check-duplication:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Pylint
        run: pip install pylint

      - name: Verificar Código Duplicado, Elif (Switch Statements) e Dead Code
        run: |
          pylint --fail-under=9.5 --disable=all \
          --enable=duplicate-code,no-else-return,no-else-raise,unused-import,unused-variable --min-similarity-lines=20 \
          --ignore=migrations \
          .

      - name: Verificar Formato de Módulos (Bloaters - Long Method)
        run: |
          pylint --fail-under=9.5 --disable=all \
          --enable=format --max-module-lines=500 --max-line-length=200  \
          --ignore=migrations \
          .

      - name: Instalar bandit
        run: pip install bandit

      - name: Verificar Segurança
        run: bandit -r . --exclude ./tests,./venv,./scripts
