name: Code Smells

on:
  push:
  pull_request:

jobs:
  check-duplication:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Pylint
        run: pip install pylint

      - name: Verificar Código Duplicado
        run: |
          pylint --disable=all \
          --enable=duplicate-code --min-similarity-lines=20 \
          --ignore=migrations \
          --load-plugins=pylint_django \
          .

      - name: Verificar Formato de Módulos (Bloaters - Long Method)
        run: |
          pylint --disable=all \
          --enable=format --max-module-lines=500 --max-line-length=200 \
          --ignore=migrations \
          --load-plugins=pylint_django \
          .

      - name: Verificar Elifs (Object-Orientation Abusers - Switch Statements)
        run: |
          pylint --disable=all \
          --enable=elif --max-nested-blocks=4 \
          --ignore=migrations \
          --load-plugins=pylint_django \
          .