name: SonarQube Analysis

on:
  push:
  pull_request:

jobs:
  sonar:
    name: Run SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Rodar análise SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=Felipe-CF_CrohNet
            -Dsonar.organization=Felipe-CF
        env:
          SONAR_TOKEN: ${{ secrets.CROH_NET_SECRET }}
